version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: production
    steps:
      - checkout
      - run: yarn
      - run: yarn prettier "./**/*.js" -l
      - run: yarn xo
